l=list('CAGGTCGGCAGACCGACCCTCATGGAAACCCCGGCCTGGCGCCGGGGTTTTCTTTTTGCGCCAGGTAGCCTGGATACGGGCGCCAGGGGTGCCTTGCCAAGGTGTGGCCGAGCCCCGGTTACTCGCCGGCATTGGCACCCTGGACCCGGGCCTCCTGGCGGCGTGGCACCGCTTCTGTGGGCAGCGGTCGCCGGTCGGTTCGGTCGATCGTTGCCAGCCGGCCTTGCTTTGCGCCTCGCGTGAAAACAAGAAGCCCCGCTATGGCGGGGCTTCTTTTATCGAATCGGCGCACAGTACGCCTTGCAGGGGGCTTTGCGGCCCT')
print(([index for index, value in enumerate(l,1)  if value=='A']))
print(list([i,l.count(i)] for i in set(l)))
print({i:l.count(i) for i in l})




A='engineera'
d={}
for i in A:
    d[i]=([index for index, value in enumerate(A,1)  if value==i])
print(d)




